### ISSUE TITLE
More than 64 processors

### ISSUE THREAD

**Issue by KellanHiggins** [thelinuxlich/artemis_CSharp#93]
I have more than 64 processors in my game and I discovered a bug where the flags aren't set up correctly for the bit system manager.

Super easy fix though. In SystemBitManager.cs you need a replacement of

```
bit = 1L << this.position;
```
with 
```
bit = BigInteger.One << this.position;
```

in the else statement. I guess no one has built a game with so many processors yet?

1L (1 64int) was looping over after it was shifted 64 bits. With the fix, we are using the as-large-as-needed integer to set the correct flag.

My branch requires me to add something to IComponent, so I can't make a pull request. Can someone else make this change?

**Comment by Maximusya** [comment]
Sure this was an oversight at the time overflow check was added.
But I'll just add a reference to #46 before anyone patches this one.

**Comment by KellanHiggins** [comment]
Not sure what you mean. This shouldn't be patched? Without the patch, inconsistent results will happen. Processors will attempt to load items into their active items that aren't relevant to their own entities.

If someone wants to limit to 64 processors, we can add another hashtag-if statement for memory reasons.

**Comment by Maximusya** [comment]
It should be patched. Just not sure about another hashtag)

**Comment by KellanHiggins** [comment]
Ohh okay. The other option is to use byte arrays instead but that would take a lot more code and refactoring. All the bitwise operators would be more complex since each time a flag is compared, the byte array would need to be unpacked. May be able to fix this problem by creating a new struct type instead of using the class BigInt.

**Comment by GrafSeismo** [comment]
with "processors" you mean Entity Systems?

**Comment by KellanHiggins** [comment]
Yeah Processors == Entity Systems. Anything that goes through entities with components and does stuff to them.

There are targets that have less than BigIntegers, but where this code would be inserted would be used only for larger than 64 flags.

**Comment by GrafSeismo** [comment]
I am sorry but may i do not get the point with, "where this code would be inserted would be used only for larger than 64 flags". You are talking about your solution?

I myself wondering about the huge amount of Systems. I do not use a System for each Component, but Systems that handle more than one Component. Maybe you can help your self a bit with using Aspects and/or reducing the amout of Systems by combining the use of Components? For e.g. If you have two Components and two related Systems that are always used together for specific Entities you can combine at least the two Systems to one System and this would economize the overhead for Systems management.

On the other hand why should we limit our self by the number of Systems which have a big overhead and slow down the overall performance on XNA supported platforms. There came other aspects like parallel processed systems on multi cores. This smells like we have to think about a redesign of several aspects or the whole framework...

I am an autodidact in programming and i do not know the tricks from the college-man to solve this quick, but i always ask myself whether i do it right and try to learn from my errors. Our error was that we could not suggest that 64 possible Systems could become a real bottleneck. At this point we have to think about a quick reference for unlimited amout of Entities, Components and Systems without the limitations of smaller computers or tiny memory. Maybe we can pull out much more when we build up a new Entity System Framework based on WinRT / UWP without the support of dead solutions like XNA (/ C#). Maybe Unity5 supports more than 64 Systems? That this artimes framework is available for Unity5 is a bit strange to me due to the fact that Unity5 is already based on ES principles.

**Comment by KellanHiggins** [comment]
In the current SystemBitManager one can limit the number of systems used to just 32 by using FORCE32 at compile time.

```
public BigInteger GetBitFor(EntitySystem entitySystem)
        {
            BigInteger bit;
            if (this.systemBits.TryGetValue(entitySystem, out bit) == false)
            {
#if WINDOWS_PHONE || XBOX || PORTABLE || FORCEINT32
                if (this.position == 32)
                {
                    // bit is going to overflow and become 1 again
                    throw new InvalidOperationException("EntitySystem instances limit reached: number of EntitySystem instances is restricted to 32 in the current Artemis build.");
                }

                bit = 1 << this.position;
#else
                bit = BigInteger.One << this.position;
#endif
                this.position++;
                this.systemBits.Add(entitySystem, bit);
                return bit;
        }
```
The else statement supports anything that is bigger than 32 bits. As the main branch stands now, there will be inconsistent results if you have more than 64 processors.

The point of Entity Systems is to move towards parallel processing and decoupling items that aren't related. Combining items and limiting the systems even on high end machines is counter. Supporting the widest possible systems is very important. This is a framework that should handle small portable devices and larger scaled servers. Currently it does.

If you have complex methods in your components, you are already moving away from entity systems. Ideally, no methods should exist in a component just data. So if this is true, how do you make any changes to just a single component. How would you render something if there is no system for it?

Not sure why you brought up building a new entity system, this is pretty specific to the C# version of Artemis. There are lots of ports to other languages for Artemis. No reason to redesign the whole framework since this one has been around a while. I will probably write an entirely new entity system sometime in the future in C++ or another programming language, but it won't affect this C# port of Artemis.

Also I didn't study CS at university either. :P.

**Comment by GrafSeismo** [comment]
Please be so kind and call them Systems, there is no "processor" in word and meaning existing in ES world.
I did not say that you have to have no System for an Component, but you are able to access any Component from any System. So you must not have a System for each Component at all, you can handle multiple Components in one or even multiple Systems. 
In your example, if you need a renderer, than take a System and call it RendererSystem. A renderer is for e.g. interested in a PositionComponent, RenderComponent and maybe some other Components too. The PositionComponent wants to be changed by MovementSystem and consumed by PlayerControlSystem (the order of Systems get interesting now) but you do not have to have a PositionSystem...

I was thinking to rewrite AES because of the initial design for XNA, which may do not fit to current needs. A WinRT solution would be the choice because it could be used in C#, C++, JavaScript, VB, etc. The target platforms are now able to handle MetroApps without specific configuration.

**Comment by thelinuxlich** [comment]
Artemis code is not tied to XNA

**Comment by Maximusya** [comment]
FORCEINT32 was introduced for performance reasons: there had been just BigInteger before.

Take, for example, C++ ECS EntityX https://github.com/alecthomas/entityx. It uses ```std::bitset<entityx::MAX_COMPONENTS>``` (64 as default to fit them all :).
Well, .NET has arbitrary large *BitArray* - but is not true bitset. Using this one would incure much more penalty than BigInteger - still anyone can forge their own fork. I'd rather keep main design as simple as it is now.

*And speaking of myself: our rather big project still fits into 32 components and 32 systems.

**Comment by GrafSeismo** [comment]
Initial design is not the limitation but the root of specific design strategies which may need to be rethink?

**Comment by KellanHiggins** [comment]
I think it would be a poor choice to start changing the underlying code for this version of C# for Artemis. All this looks like it has been discussed before and the performance trade-off has been recognized.

This isn't a discussion about if or if we should not use BigInteger, it is about fixing a bug that would cause unanticipated results that I had to grind through code to find :P.

I don't know if you are intending to be rude, but your messages definitely come off as rude. Sorry if I am confusing you by using the term processor versus system. I call them processors because they process entities or other code through each system. I think this is fine within the context of Entity Systems. I can't see how you could have a system that doesn't do some sort of processing.

Also good job @Maximusya on that. My code is slowly evolving to remove some extra systems, but I still want that flexibility of unlimited processing systems.

Also I don't use XNA at all, but I am using this strictly for a server which doesn't perform any of the graphics.

**Comment by GrafSeismo** [comment]
I am sorry for the inconvenience. If i appear to be rude, that was not my will and might be the result of my missing experience in using english in the near past. I am not a native speaker in english.
To be honest, when discussing about ES it does not make things easier (at least for me) when we have to translate anyones own wording. It seems that i got totally misunderstood and i should better shut up now. I am sure you will find anyone else to explain things better and adequate polite than me.

**Comment by KellanHiggins** [comment]
Oh okay, I am sorry for being a jerk then. I will try and use clearer English. :).
